---
# tasks file for db
- name: Change mongo config file
  template:
    src: templates/mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644 # <-- file permissions to install
  notify: restart mongod
- name: Show info about the env this host belongs to
  debug: msg="This host is in {{ env }} environment!!!"