---
- name: Configure App # <-- description
  hosts: app # <-- to which hosts will be performed task
  become: true # <-- run as root
  vars:
    db_host: 10.132.15.225
  tasks: # <-- block of tasks that will be performed for these hosts
    - name: Add unit file for Puma
      copy: 
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: enable puma
      systemd: name=puma enabled=yes
      
    # handler which systemd will indicate that the unit for the service has changed and should by re-read
  handlers:
  - name: reload puma
    systemd: name=puma state=restarted